use std::env;
use std::fs;
use std::path::PathBuf;

/// Lab pin. Tests deploy mock Atlas at this id. Override with `ATLAS_PIN_HEX`.
const DEFAULT_ATLAS_PIN_HEX: &str =
    "c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1";

fn parse_atlas_pin_hex(s: &str) -> Result<[u8; 32], String> {
    let s = s.trim();
    if s.len() != 64 {
        return Err(format!("ATLAS_PIN_HEX must be 64 hex chars, got {}", s.len()));
    }
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16)
            .map_err(|e| format!("invalid hex at byte {i}: {e}"))?;
    }
    Ok(out)
}

fn main() {
    let hex = match env::var("ATLAS_PIN_HEX") {
        Ok(s) if !s.trim().is_empty() => s,
        _ => DEFAULT_ATLAS_PIN_HEX.to_string(),
    };
    let bytes = parse_atlas_pin_hex(&hex).expect("ATLAS_PIN_HEX");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("atlas_pin.rs");
    let body = format!(
        "/// Generated by build.rs — do not edit.\npub const ATLAS_ID_BYTES: [u8; 32] = {:?};\n",
        bytes
    );
    fs::write(&dest, body).expect("write atlas_pin.rs");
    println!("cargo:rerun-if-env-changed=ATLAS_PIN_HEX");
}
